language: julia

os:
  - linux
  - osx

julia:
  - 1.1
  - 1.2
  - 1.3
  - nightly

branches:
  only:
  - master

notifications:
  email: false

script:
  - julia --project --color=yes -e 'using Pkg;
                                    Pkg.instantiate();
                                    Pkg.add([PackageSpec(name = "TerminalRegressionTests", url="https://github.com/pfitzseb/TerminalRegressionTests.jl.git", rev = "sp/betterdiffs"),
                                             PackageSpec(name = "VT100", rev = "master")]);
                                    Pkg.build;
                                    Pkg.test();'
